version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: ./node
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql

  php:
    build:
      context: ./php
    ports:
      - '80:80'
    volumes:
      - ./php:/var/www/html

volumes:
  mysql-data:
